<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DetaljiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $detalji = [
            [
            
                'detalji_id' => 1,
                'karoserija' => 'džip',
                'broj_vrata' => 5,
                'broj_sedista' => 5,
                'menjac' => 'Automatski',
                'vrsta_goriva' => 'Benzin',
                'potrosnja' => 9.2,
                'klima' => 'Automatski',
                'pogon' => '4x4',
                'snaga_motora' => 250,
                'ubrazanje' => 6.2,
                'maks_brzina' => 245,
                'duzina' => 4.92,
                'sirina' => 1.98,
                'visina' => 1.69,
                'teznina_praznog' => 1985,
                'maks_opter' => 845,
            ],
            [
                'detalji_id' => 2,
                'karoserija' => 'džip',
                'broj_vrata' => 5,
                'broj_sedista' => 5,
                'menjac' => 'Automatski',
                'vrsta_goriva' => 'Dizel',
                'potrosnja' => 8.9,
                'klima' => 'Automatski',
                'pogon' => '4x4',
                'snaga_motora' => 243,
                'ubrazanje' => 6.4,
                'maks_brzina' => 210,
                'duzina' => 4.82,
                'sirina' => 1.93,
                'visina' => 1.96,
                'teznina_praznog' => 2376,
                'maks_opter' => 774,
            ],
            [
                'detalji_id' => 3,
                'karoserija' => 'hečbek',
                'broj_vrata' => 5,
                'broj_sedista' => 5,
                'menjac' => 'Manuelni',
                'vrsta_goriva' => 'Benzin',
                'potrosnja' => 4.9,
                'klima' => 'Manuelni',
                'pogon' => 'Prednji',
                'snaga_motora' => 81,
                'ubrazanje' => 10.2,
                'maks_brzina' => 202,
                'duzina' => 4.28,
                'sirina' => 1.78,
                'visina' => 1.49,
                'teznina_praznog' => 1141,
                'maks_opter' => 579,
            ],
                [
                    'detalji_id' => 4,
                    'karoserija' => 'limuzina',
                    'broj_vrata' => 5,
                    'broj_sedista' => 5,
                    'menjac' => 'Manuelni',
                    'vrsta_goriva' => 'Benzin',
                    'potrosnja' => 6.7,
                    'klima' => 'Automatski',
                    'pogon' => 'Prednji',
                    'snaga_motora' => 225,
                    'ubrazanje' => 6.4,
                    'maks_brzina' => 250,
                    'duzina' => 0,
                    'sirina' => 0,
                    'visina' => 0,
                    'teznina_praznog' => 0,
                    'maks_opter' => 0,
                ],
                [
                    'detalji_id' => 5,
                    'karoserija' => 'džip',
                    'broj_vrata' => 5,
                    'broj_sedista' => 5,
                    'menjac' => 'Manuelni',
                    'vrsta_goriva' => 'Benzin',
                    'potrosnja' => 6.5,
                    'klima' => 'Automatski',
                    'pogon' => 'Prednji',
                    'snaga_motora' => 150,
                    'ubrazanje' => 8.9,
                    'maks_brzina' => 204,
                    'duzina' => 4.45,
                    'sirina' => 1.83,
                    'visina' => 1.52,
                    'teznina_praznog' => 1362,
                    'maks_opter' => 598,
                ],
                [
                    'detalji_id' => 6,
                    'karoserija' => 'Limuzina',
                    'broj_vrata' => 5,
                    'broj_sedista' => 5,
                    'menjac' => 'Automatski',
                    'vrsta_goriva' => 'Dizel',
                    'potrosnja' => 4.6,
                    'klima' => 'Automatski',
                    'pogon' => '4x4',
                    'snaga_motora' => 190,
                    'ubrazanje' => 6.9,
                    'maks_brzina' => 233,
                    'duzina' => 4.7,
                    'sirina' => 1.82,
                    'visina' => 1.44,
                    'teznina_praznog' => 1540,
                    'maks_opter' => 630,
                ],
                    [
                        'detalji_id' => 7,
                        'karoserija' => 'Džip',
                        'broj_vrata' => 5,
                        'broj_sedista' => 5,
                        'menjac' => 'Automatski',
                        'vrsta_goriva' => 'Dizel',
                        'potrosnja' => 8.5,
                        'klima' => 'Automatski',
                        'pogon' => '4x4',
                        'snaga_motora' => 249,
                        'ubrazanje' => 7.6,
                        'maks_brzina' => 210,
                        'duzina' => 4.85,
                        'sirina' => 2.07,
                        'visina' => 1.78,
                        'teznina_praznog' => 2136,
                        'maks_opter' => 897,
                    ],
                    [
                        'detalji_id' => 8,
                        'karoserija' => 'džip',
                        'broj_vrata' => 5,
                        'broj_sedista' => 5,
                        'menjac' => 'Automatski',
                        'vrsta_goriva' => 'Dizel',
                        'potrosnja' => 7.4,
                        'klima' => 'Automatski',
                        'pogon' => '4x4',
                        'snaga_motora' => 330,
                        'ubrazanje' => 5.7,
                        'maks_brzina' => 240,
                        'duzina' => 4.93,
                        'sirina' => 2.01,
                        'visina' => 1.73,
                        'teznina_praznog' => 2220,
                        'maks_opter' => 820,
                    ],
                        [
                            'detalji_id' => 9,
                            'karoserija' => 'Limuzina',
                            'broj_vrata' => 5,
                            'broj_sedista' => 5,
                            'menjac' => 'Automatski',
                            'vrsta_goriva' => 'Dizel',
                            'potrosnja' => 6.5,
                            'klima' => 'Automatski',
                            'pogon' => '4x4',
                            'snaga_motora' => 243,
                            'ubrazanje' => 5.4,
                            'maks_brzina' => 250,
                            'duzina' => 5.28,
                            'sirina' => 1.95,
                            'visina' => 1.5,
                            'teznina_praznog' => 1860,
                            'maks_opter' => 685,
                        ],
                        [
                            'detalji_id' => 10,
                            'karoserija' => 'džip',
                            'broj_vrata' => 5,
                            'broj_sedista' => 7,
                            'menjac' => 'Automatski',
                            'vrsta_goriva' => 'Dizel',
                            'potrosnja' => 7.4,
                            'klima' => 'Automatski',
                            'pogon' => '4x4',
                            'snaga_motora' => 435,
                            'ubrazanje' => 4.9,
                            'maks_brzina' => 250,
                            'duzina' => 5.06,
                            'sirina' => 1.96,
                            'visina' => 1.74,
                            'teznina_praznog' => 2330,
                            'maks_opter' => 870,
                        ],
                    
                    ];
        DB::table('detalji')->insert($detalji);
    }
}
